const NAMELIST = [
    "Earth (C-137)",
    "Abadango",
    "Citadel of Ricks",
    "Worldender's lair",
    "Anatomy Park",
    "Interdimensional Cable",
    "Immortality Field Resort",
    "Post-Apocalyptic Earth",
    "Purge Planet",
    "Venzenulon 7",
    "Bepis 9",
    "Cronenberg Earth",
    "Nuptia 4",
    "Giant's Town",
    "Bird World",
    "St. Gloopy Noops Hospital",
    "Earth (5-126)",
    "Mr. Goldenfold's dream",
    "Gromflom Prime",
    "Earth (Replacement Dimension)",
    "Testicle Monster Dimension",
    "Signus 5 Expanse",
    "Earth (C-500A)",
    "Rick's Battery Microverse",
    "The Menagerie",
    "Earth (K-83)",
    "Hideout Planet",
    "Unity's Planet",
    "Dorian 5",
    "Earth (Unknown dimension)",
    "Earth (J19ζ7)",
    "Roy: A Life Well Lived",
    "Eric Stoltz Mask Earth",
    "Earth (Evil Rick's Target Dimension)",
    "Planet Squanch",
    "Glaagablaaga",
    "Resort Planet",
    "Interdimensional Customs",
    "Galactic Federation Prison",
    "Gazorpazorp",
    "Hamster in Butt World",
    "Earth (Giant Telepathic Spiders Dimension)",
    "Alphabetrium",
    "Jerryboree",
    "Krootabulon",
    "Zigerion's Base",
    "Pluto",
    "Fantasy World",
    "Zeep Xanflorp's Miniverse",
    "Kyle's Teenyverse",
    "Larva Alien's Planet",
    "Earth (K-22)",
    "Mr. Meeseeks Box",
    "Vindicator's Base",
    "Pawn Shop Planet",
    "Mega Gargantuan Kingdom",
    "Gear World",
    "Earth (D-99)",
    "Earth (D716)",
    "Earth (D716-B)",
    "Earth (D716-C)",
    "Earth (J-22)",
    "Froopyland",
    "Detoxifier",
    "Trunk World",
    "Plopstar",
    "Blips and Chitz",
    "Girvonesk",
    "Earth (C-35)",
    "Snuffles' Dream",
    "Earth (Pizza Dimension)",
    "Earth (Phone Dimension)",
    "Greasy Grandma World",
    "Earth (Chair Dimension)",
    "Árboles Mentirosos",
    "Alien Day Spa",
    "Earth (Fascist Dimension)",
    "Snake Planet",
    "Forbodulon Prime",
    "Earth (Fascist Shrimp Dimension)",
    "Earth (Fascist Teddy Bear Dimension)",
    "Earth (Wasp Dimension)",
    "Monogatron Mothership",
    "Gorgon Quadrant",
    "Midland Quasar",
    "Mount Space Everest",
    "Globaflyn",
    "Heist-Con",
    "Heistotron Base",
    "Mount Olympus",
    "Plitzville Montana",
    "Earth (Tusk Dimension)",
    "Gramuflack",
    "Draygon",
    "New Improved Galactic Federation Quarters",
    "Story Train",
    "Non-Diegetic Alternative Reality",
    "Tickets Please Guy Nightmare",
    "Morty’s Story",
    "Ricks’s Story",
    "Glorzo Asteroid",
    "Alien Acid Plant",
    "Merged Universe",
    "Near-Duplicate Reality",
    "NX-5 Planet Remover",
    "Gaia",
    "Defiance's Ship",
    "Defiance's Base",
    "The Ocean",
    "Narnia Dimension",
    "Elemental Rings",
    "Morglutz",
    "Ferkus 9",
    "Morty",
    "Space",
    "Hell",
    "Z. Q. P. D.",
    "Space Tahoe",
    "France",
    "Birdperson's Consciousness",
    "Rick's Consciousness",
    "Avian Planet",
    "Normal Size Bug Dimension",
    "Slartivart",
    "Rick and Two Crows Planet",
    "Rick's Memories"
]
const TYPELIST = [
    "Planet",
    "Cluster",
    "Space station",
    "Microverse",
    "TV",
    "Resort",
    "Fantasy town",
    "Dream",
    "Dimension",
    "unknown",
    "Menagerie",
    "Game",
    "Customs",
    "Daycare",
    "Dwarf planet (Celestial Dwarf)",
    "Miniverse",
    "Teenyverse",
    "Box",
    "Spacecraft",
    "Artificially generated world",
    "Machine",
    "Arcade",
    "Spa",
    "Quadrant",
    "Quasar",
    "Mount",
    "Liquid",
    "Convention",
    "Woods",
    "Diegesis",
    "Non-Diegetic Alternative Reality",
    "Nightmare",
    "Asteroid",
    "Acid Plant",
    "Reality",
    "Death Star",
    "Base",
    "Elemental Rings",
    "Human",
    "Space",
    "Hell",
    "Police Department",
    "Country",
    "Consciousness",
    "Memory"
]
const DIMENSIONLIST = [
    "Dimension C-137",
    "unknown",
    "Post-Apocalyptic Dimension",
    "Replacement Dimension",
    "Cronenberg Dimension",
    "Fantasy Dimension",
    "Dimension 5-126",
    "Testicle Monster Dimension",
    "Cromulon Dimension",
    "Dimension C-500A",
    "Dimension K-83",
    "Dimension J19ζ7",
    "Eric Stoltz Mask Dimension",
    "Evil Rick's Target Dimension",
    "Giant Telepathic Spiders Dimension",
    "Unknown dimension",
    "Dimension K-22",
    "Dimension D-99",
    "Dimension D716",
    "Dimension D716-B",
    "Dimension D716-C",
    "Dimension J-22",
    "Dimension C-35",
    "Pizza Dimension",
    "Phone Dimension",
    "Chair Dimension",
    "Fascist Dimension",
    "Fascist Shrimp Dimension",
    "Fascist Teddy Bear Dimension",
    "Wasp Dimension",
    "Tusk Dimension",
    "Magic Dimension",
    "Merged Dimension",
]

/**
 * Recurso que tiene información sobre las ubicaciones.
 * @return {Object} Objeto que contiene información de las ubicaciones.
 * @property {Array} NAMELIST - Indica el array con los nombres de las ubicaciones.
 * @property {Array} TYPELIST - Indica los tipos de ubicaciones.
 * @property {Array} DIMENSIONLIST - Indica las dimensiones de las ubicaciones. 
 */
const listLocation = () => {
    const NAMELISTORDEN = NAMELIST.sort()
    const TYPELISTORDEN = TYPELIST.sort()
    const DIMENSIONLISTORDEN = DIMENSIONLIST.sort()
    return {NAMELIST: NAMELISTORDEN, TYPELIST: TYPELISTORDEN, DIMENSIONLIST: DIMENSIONLISTORDEN}
}
export default listLocation
